const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',

    GET_POSTS: 'GET_POSTS',
    GET_LIMIT_POSTS: 'GET_LIMIT_POSTS',
    GET_NEW_POSTS: 'GET_NEW_POSTS',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICE: 'GET_PRICE',
    GET_ACREAGE: 'GET_ACREAGE',

}

export default actionTypes